-- ============================================
-- Barangay Pinyahan Website Database Schema
-- MySQL / MariaDB
-- ============================================


-- ============================================
-- 1. ADMINS TABLE
-- ============================================
CREATE TABLE admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status ENUM('online', 'offline') DEFAULT 'offline',
    role VARCHAR(50) DEFAULT 'Administrator',
    requires_password_change BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================
-- 2. COMPLAINTS TABLE
-- ============================================
CREATE TABLE complaints (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ref_no VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    complaint_type VARCHAR(100) NOT NULL,
    category VARCHAR(50) DEFAULT NULL,
    message TEXT NOT NULL,
    photo_url VARCHAR(255) DEFAULT NULL,
    status ENUM('Pending', 'On-Going', 'Resolved') DEFAULT 'Pending',
    urgency_level ENUM('Low', 'Medium', 'High') DEFAULT 'Low',
    admin_notes TEXT DEFAULT NULL,
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    resolved_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================
-- 3. NEWS TABLE
-- ============================================
CREATE TABLE news (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date_published DATE NOT NULL,
    description TEXT NOT NULL,
    photo_url VARCHAR(255) DEFAULT NULL,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================
-- 4. EVENTS TABLE
-- ============================================
CREATE TABLE events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    location VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    photo_url VARCHAR(255) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================
-- 5. SERVICES TABLE
-- ============================================
CREATE TABLE services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    icon_class VARCHAR(50) DEFAULT 'fas fa-file-alt',
    icon_color VARCHAR(20) DEFAULT 'blue',
    requirements JSON DEFAULT NULL,
    procedures JSON DEFAULT NULL,
    status ENUM('Active', 'Inactive') DEFAULT 'Active',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================
-- 6. NOTIFICATIONS TABLE
-- ============================================
CREATE TABLE notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id INT DEFAULT NULL,
    title VARCHAR(100) NOT NULL,
    message VARCHAR(255) NOT NULL,
    icon_class VARCHAR(50) DEFAULT 'fas fa-bell',
    is_read BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE SET NULL
);

-- ============================================
-- 7. AUDIT LOGS TABLE
-- ============================================
CREATE TABLE audit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id INT,
    action_type VARCHAR(50) NOT NULL,
    action_details VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE SET NULL
);

-- ============================================
-- SEED DATA
-- ============================================

-- Default admin account (password: admin123)
-- NOTE: Replace this hash with a real bcrypt hash generated by your backend
INSERT INTO admins (username, full_name, email, password_hash, status, role, created_at) VALUES
('JohnDoe_1', 'John Doe', 'johndoe@gmail.com', '$2b$10$placeholder_hash_replace_me', 'online', 'Administrator', '2026-01-07'),
('JaneReyes_2', 'Jane Reyes', 'janereyes@gmail.com', '$2b$10$placeholder_hash_replace_me', 'online', 'Administrator', '2026-01-10'),
('JohnLopez_3', 'John Lopez', 'johnlopez@gmail.com', '$2b$10$placeholder_hash_replace_me', 'online', 'Administrator', '2026-02-01'),
('Eleven_4', 'Eleven', 'eleven@gmail.com', '$2b$10$placeholder_hash_replace_me', 'offline', 'Administrator', '2026-02-05'),
('Mike_5', 'Mike', 'mike@gmail.com', '$2b$10$placeholder_hash_replace_me', 'offline', 'Administrator', '2026-02-12');

-- Sample complaints
INSERT INTO complaints (ref_no, full_name, address, contact_number, complaint_type, category, message, status, urgency_level, submitted_at) VALUES
('BRGY-2026-001', 'Juan Dela Cruz', '18 Malakas St.', '09171234567', 'security', 'Peace & Order', 'I would like to complain about the commotion happened in our area.', 'On-Going', 'High', '2026-01-07 16:00:00'),
('BRGY-2026-002', 'Jane Reyes', '25 Matapang St.', '09181234567', 'trash', 'Sanitation', 'There is uncollected garbage in our street for 3 days already.', 'Pending', 'Medium', '2026-01-07 16:30:00'),
('BRGY-2026-003', 'John Lopez', '30 Magalang St.', '09191234567', 'other', 'Others', 'Street light in our area has been broken for a week.', 'Pending', 'Low', '2026-01-07 17:00:00');

-- Sample news
INSERT INTO news (title, date_published, description, photo_url, is_featured) VALUES
('Fire Hits DPWH Office in Barangay Pinyahan', '2025-10-22', 'A massive fire broke out at the Department of Public Works and Highways (DPWH) Bureau of Research and Standards building along NIA Road in Barangay Pinyahan, Quezon City, on October 22, 2025. The blaze quickly reached the third alarm, requiring more than 25 fire trucks to bring it under control. While the fire caused significant damage to the building and destroyed various pieces of research equipment, authorities reported no casualties or injuries.', NULL, TRUE);

-- Sample events
INSERT INTO events (name, date, time, location, description) VALUES
('Barangay Clean-Up Drive 2026', '2026-02-15', '16:00:00', 'Brgy. Court', 'We\'re happy to have you here! This space was created to keep our community informed, connected, and involved. Whether you\'re looking for the latest announcements, ongoing projects, public services, or ways to participate in our programs, everything you need is just a few clicks away.');

-- Sample services
INSERT INTO services (name, description, icon_class, icon_color, requirements, procedures, status) VALUES
('Barangay Clearance', 'Service Information and Processing Details', 'fas fa-file-alt', 'blue',
 '["Barangay Clearance Application Form", "Valid Government-issued ID", "Proof of Residency", "Cedula (Community Tax Certificate)"]',
 '["Submit requirements to the Barangay Office", "Verification of documents", "Pay clearance fee", "Processing and approval", "Release of Barangay Clearance"]',
 'Active'),
('Business Permit Application', 'Accept and process business permit applications.', 'fas fa-building', 'blue',
 '["Barangay Business Permit Application Form", "DTI/SEC Registration", "Valid Government-issued ID", "Cedula", "Proof of Business Address"]',
 '["Submit requirements to the Barangay Office", "Verification of documents", "Pay permit fee", "Inspection (if applicable)", "Processing and approval", "Release of Business Permit"]',
 'Active'),
('Certificate of Indigency', 'Provide certificates of indigency for residents.', 'fas fa-certificate', 'blue',
 '["Certificate of Indigency Request Form", "Valid Government-issued ID", "Proof of Residency"]',
 '["Submit requirements to the Barangay Office", "Verification of documents", "Processing and approval", "Release of Certificate"]',
 'Active'),
('Health Services', 'Offer health services and medical assistance.', 'fas fa-heart', 'red',
 '["Valid ID", "Barangay ID or Proof of Residency", "Medical Records (if applicable)"]',
 '["Visit the Barangay Health Center", "Register at the reception", "Consultation with health worker", "Receive prescribed medication or referral"]',
 'Active'),
('Disaster Response', 'Coordinate disaster response and relief efforts.', 'fas fa-house-damage', 'yellow',
 '["Valid ID", "Proof of Residency", "Damage Assessment Form (if applicable)"]',
 '["Report to the Barangay Disaster Risk Reduction Office", "Fill out assessment form", "Evaluation of damage/need", "Distribution of relief goods or assistance"]',
 'Active');

-- Sample notifications
INSERT INTO notifications (admin_id, title, message, icon_class, is_read) VALUES
(NULL, 'New Complaint', 'A new complaint has been submitted.', 'fas fa-bell', FALSE),
(NULL, 'System Update', 'Your system has an update available.', 'fas fa-cog', TRUE);

-- Sample audit logs
INSERT INTO audit_logs (admin_id, action_type, action_details) VALUES
(1, 'Complaint', 'Resolved Complaint #BRGY-2026-001 (Juan Dela Cruz)'),
(2, 'Service', 'Updated requirements for Barangay Clearance'),
(1, 'Event', 'Created new event: Barangay Clean-Up Drive 2026');
